# Generated by Django 5.1 on 2024-08-24 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="house_number",
            field=models.CharField(max_length=15, verbose_name="Номер дома"),
        ),
    ]
